Algoritmo "coordenadas"

Var
x,y: inteiro


Inicio
escreval ("Digite as cordenadas X e Y ")
leia (X)
leia (Y)

se (x > 0)e(y > 0) entao

escreva ("Q1")

senao
se (x < 0)e(y>0) entao
escreva ("Q2")

senao
se (x < 0)e(y<0) entao
escreva ("Q3")

senao
se (x>0)e(y<0)entao
escreva ("Q4")

senao
       escreva ("Origem")
       
                         fimse
                         fimse
                         fimse
                         fimse

Fimalgoritmo