Algoritmo "crescente"

Var

   x,y: inteiro

Inicio

     escreval("Digite valor de x e y: ")
     leia (x)
     leia (y)
     
      enquanto x <> y faca
      
      se x > y entao
      escreval (x, y," Decrescente")
      
      senao

      escreval (x, y," Crescente")
      
      fimse
      
      Escreval ("Digite mais dois numeros:")
      leia (x)
      leia (y)
      
      fimenquanto
      
      
     
     

Fimalgoritmo