Algoritmo "tabuada"
// Disciplina   : [Linguagem e Lógica de Programação]
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/10/2021
Var
mult,n,tab: inteiro


Inicio



escreva ("Deseja a tabuada de qual numero? ")
leia (n)

mult <- 0

 enquanto (n > 0)e(n<11)e(mult<10) faca
 
 mult <- mult + 1
 tab <- n * mult


   escreval (n," x", mult," =", tab)
 
 fimenquanto

Fimalgoritmo